/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'suraj' at '10/23/16 9:57 PM' with Gradle 2.14.1
 *
 * @author suraj, @date 10/23/16 9:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
